config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :ingredients, only: [ :index, :new, :create ]
  get 'ingredients/:name', to: 'ingredients#show'

  resources :pairs, only: [ :show, :create ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :pairs_1, class_name: "Pair", foreign_key: "ingredient_1_id"
  has_many :pairs_2, class_name: "Pair", foreign_key: "ingredient_2_id"

  def pairs
    self.pairs_1 + self.pairs_2
  end

  validates :name, presence: true, uniqueness: true
  validates :colour, presence: true
end

app/models/pair.rb
class Pair < ApplicationRecord
  belongs_to :ingredient_1, class_name: 'Ingredient'
  belongs_to :ingredient_2, class_name: 'Ingredient'
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :pair
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/foods_controller.rb
class IngredientsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find_by(name: params[:name].capitalize)
  end

  def new
  end

  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  def show
    @pair = Pair.find(params[:id])
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/index.html.erb
<h1>Foods#index</h1>
<p>Find me in app/views/foods/index.html.erb</p>

app/views/foods/new.html.erb
<h1>Foods#new</h1>
<p>Find me in app/views/foods/new.html.erb</p>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<% @ingredients.each do |ingredient| %>
  <h3><%= ingredient.name %></h3>
<% end %>

app/views/ingredients/new.html.erb
<h1>Ingredients#new</h1>
<p>Find me in app/views/foods/new.html.erb</p>

app/views/ingredients/show.html.erb
<h1>What goes with <%= @ingredient.name %>?</h1>

<% @ingredient.pairs.each do |pair| %>
  <%= link_to pair_path(pair), class: "card" do %>
    <h4><%= @ingredient == pair.ingredient_1 ? pair.ingredient_2.name : pair.ingredient_1.name %></h4>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pairs/show.html.erb
<h1>
  <span style="color:<%= @pair.ingredient_1.colour %>"><%= @pair.ingredient_1.name %></span>
   and
   <span style="color:<%= @pair.ingredient_2.colour %>"><%= @pair.ingredient_2.name %></span>
</h1>
<ul>
  <li>Classic combo: <%= @pair.classic %></li>
  <li>Something different: <%= @pair.different %></li>
  <li>So-so: <%= @pair.average %></li>
  <li>Bad idea: <%= @pair.bad %></li>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "What goes with...?", root_path, class: "font-hand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>